apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-env-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameter-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-env-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: /k8s/attdm/db_name
    - secretKey: DB_USER
      remoteRef:
        key: /k8s/attdm/db_user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /k8s/attdm/db_password
